### PR TITLE
add missing deps and pip check

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Downstream, seeing:
```
ipycytoscape 1.2.1 requires neotime, which is not installed.
ipycytoscape 1.2.1 requires py2neo, which is not installed.
```

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
ick, full yarn install and rebuild...

**Comment by marimeireles** [comment]
> ick, full yarn install and rebuild...

What do you mean by that?

And thanks for catching this!
In my local env I'm using the pip package and I have no issues.
I think the `py2neo` feedstock is unmaintained, just asked for permission to be a contributor there. But while this doesn't happen... I was wondering if just downloading it from `pip` would work, but I don't really know how to do it.
Something like this:

`script: {{ PYTHON }} -m pip install . -vv && pip install py2neo==2021.1.1`

doesn't work. Do you? I can also ask around!

Thanks again =)

**Comment by bollwyvl** [comment]
> What do you mean by that?

Welp, the sdist already has all the built assets. Having a build-time dependency on nodejs, and then re-solving and rebuilding everything without really testing it, is... perilous. Frankly i'm not a huge fan of `jupyter-packaging` as a `build`/`host`, but _certainly not_ a `run`, dependency, but that's a story for another feedstock...

> just downloading it from pip would work

nope. I mean theoretically, but not really that great from an ecosystem perspective. certainly not a hard pin like that for a hard run dependency...

Given these are lazily-imported dependencies, and i suspect one needs an actual neo4j to do anything with them, perhaps marking them as `extras` upstream is the quickest course to getting something that doesn't break users' environments that rely on conda-forge. anyhow, in my stuff, i've pinned down to a version that doesn't contain this, but have probably had enough fun here for one day...

**Comment by marimeireles** [comment]
This sounds like a reasonable solution to me. I'll change it upstream. Thank you @bollwyvl! :cherry_blossom:

**Comment by marimeireles** [comment]
I released a new version with your proposed fixes.
Thank you for the PR and the heads up Nicholas! :)

**Pull request closed without merging**
