### PR TITLE
Add npmjs

### PR DESCRIPTION
**Pull request by SylvainCorlay**
The static assets are not properly included in the conda package.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
cc @jtpio there seems to be some issue with jupyterlab 2.0

```shell
src/plugin.ts(29,3): error TS2322: Type 'Token<IJupyterWidgetRegistry>[]' is not assignable to type 'Token<any>[]'.
    Type 'Token<IJupyterWidgetRegistry>' is not assignable to type 'Token<any>'.
      Types have separate declarations of a private property '_tokenStructuralPropertyT'.
```

**Comment by marimeireles** [comment]
Hm!
Sorry  for missing that  @SylvainCorlay, the  recipes I looked at didn't have stuff like this.  Why do we need nodejs here? For npm?

**Comment by jtpio** [comment]
@SylvainCorlay see:

- https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/60#issuecomment-597141429
- https://github.com/jupyter-widgets/ipywidgets/issues/2798#issuecomment-592531036

We might want to cast `as any` here for the time being:

https://github.com/QuantStack/ipycytoscape/blob/a94cd4100908e7991415f822c3ab768c9d2427a5/src/plugin.ts#L29

**Comment by jtpio** [comment]
@marimeireles yes nodejs is needed to build the frontend

**Comment by SylvainCorlay** [comment]
> @marimeireles yes nodejs is needed to build the front-end

In the case of the js cookiecutter, we don't rebuild the front-end which is included in the sdist...

I am not sure I like the logic of the new ts cookiecutter very much.

**Pull request merged**
